ALTER TABLE interviews ADD COLUMN IF NOT EXISTS program_id BIGINT;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS session_id BIGINT;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS practice_id BIGINT;
